### ISSUE TITLE
Deprecated function from dplyr

### ISSUE THREAD

**Issue by PierreMasselot** [guyabel/wcde#3]
It seems that the function `get_wcde` makes some use of `dplyr::summarise` that is now deprecated. Some computation in the function probably returns more than a signle value, which is not supported anymore in `dplyr::summarise` and should be handled by `dplyr::reframe`.

For context, I downloaded some data today and got the following warnign message.

```r
Warning message:                                                                                                       
Returning more (or less) than 1 row per `summarise()` group was deprecated in dplyr 1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()` always returns an ungrouped data frame and
  adjust accordingly.
ℹ The deprecated feature was likely used in the wcde package.
  Please report the issue at <https://github.com/guyabel/wcde/issues/>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
```

Thanks!

**Comment by guyabel** [comment]
The function is updated in the development version `devtools::install_github("guyabel/wcde")` . Will probably move to CRAN in a few weeks.
